/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiSummary: typeof import('./src/components/ai/AiSummary.vue')['default']
    AnalysisChart: typeof import('./src/components/ai/AnalysisChart.vue')['default']
    AuroraBackground: typeof import('./src/components/common/AuroraBackground.vue')['default']
    AuroraButton: typeof import('./src/components/common/AuroraButton.vue')['default']
    BentoCard: typeof import('./src/components/common/BentoCard.vue')['default']
    ChatBubble: typeof import('./src/components/chat/ChatBubble.vue')['default']
    ChatSidebar: typeof import('./src/components/chat/ChatSidebar.vue')['default']
    ChunkUpload: typeof import('./src/components/upload/ChunkUpload.vue')['default']
    DocumentCompare: typeof import('./src/components/document/DocumentCompare.vue')['default']
    DropUpload: typeof import('./src/components/upload/DropUpload.vue')['default']
    FileVersionModal: typeof import('./src/components/file/FileVersionModal.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    KeywordTags: typeof import('./src/components/ai/KeywordTags.vue')['default']
    KnowledgeGraph: typeof import('./src/components/ai/KnowledgeGraph.vue')['default']
    ProcessProgress: typeof import('./src/components/document/ProcessProgress.vue')['default']
    QuickProcess: typeof import('./src/components/QuickProcess.vue')['default']
    RecentDocuments: typeof import('./src/components/document/RecentDocuments.vue')['default']
    RippleEffect: typeof import('./src/components/common/RippleEffect.vue')['default']
    RippleLoader: typeof import('./src/components/common/RippleLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultPanel: typeof import('./src/components/layout/SearchResultPanel.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Skeleton: typeof import('./src/components/common/Skeleton.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    VersionCompareModal: typeof import('./src/components/file/VersionCompareModal.vue')['default']
    VersionSelectModal: typeof import('./src/components/upload/VersionSelectModal.vue')['default']
  }
}
