FROM eclipse-temurin:17-jdk-alpine

LABEL maintainer="qxk"

# 设定时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone

# 复制jar包到容器内
COPY document-service/target/document-service-1.0.0.jar /app/document-service.jar

# 设定工作目录
WORKDIR /app

# 暴露端口
EXPOSE 8084

# 启动应用
CMD ["java", "-jar", "document-service.jar"]
